### PR TITLE
[BUGS-3216] Avoid a fatal error if views_ui is disabled.

### PR DESCRIPTION
**Pull request by sarahg**
This pulls in the updated version of the ViewsCount check from Site Audit 8.x-3.x ([source](https://git.drupalcode.org/project/site_audit/-/blob/8.x-3.x/src/Plugin/SiteAuditCheck/ViewsCount.php)).

This bug was reported and fixed for 8.x-3.x here: https://www.drupal.org/project/site_audit/issues/3104713

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
LGTM, let's just get the tests green. See comments in #14

**Comment by greg-1-anderson** [comment]
composer require is not a good way to install Composer. Follow the install instructions to install to another location, and then call Composer via its full path. That would be a pain! Might be easier to fix composer-test-scenarios.

Maybe you should just work with the PHP 56 tests for now. I'll see if I have time to fix composer-test-scenarios later -- but I don't know if I can get to that this week.

**Comment by greg-1-anderson** [comment]
@sarahg Maybe Travis will allow `sudo composer selfupdate --1`?

**Comment by sarahg** [comment]
@greg-1-anderson I think I got it!! Can you please take another look when you have a chance?

I merged https://github.com/pantheon-systems/site-audit-tool/pull/15 into this one already to make sure it really solved the issue at hand. If you check that one first, the only unique part of this is the first 2 commits that actually modify the Drush extension. Thank you for your patience :)

**Comment by greg-1-anderson** [comment]
Merged as #17

**Pull request closed without merging**
