### PR TITLE
Update packages for Composer 2

### PR DESCRIPTION
**Pull request by sarahg**
Updates these packages to newer releases in order to support Composer 2:

https://github.com/g1a/composer-test-scenarios (3.1.1 -> 3.2.0)
https://github.com/zaporylie/composer-drupal-optimizations (1.1.1 -> 1.2.0)

Currently, the PHP 7.x tests fail with this error:

```
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - g1a/composer-test-scenarios is locked to version 3.1.1 and an update of this package was not requested.
    - g1a/composer-test-scenarios 3.1.1 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - zaporylie/composer-drupal-optimizations is locked to version 1.1.1 and an update of this package was not requested.
    - zaporylie/composer-drupal-optimizations 1.1.1 requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
g1a/composer-test-scenarios has the same problem. I think that the path repository trick I am using in the tests might not work with Composer 2. It seems that the newer versions of php on Travis are using Composer 2 now.

If you just want to focus on fixing site_audit_tool features and not worry about Composer 2 functionality, then add to your tests:
```
composer selfupdate --1
```

**Comment by greg-1-anderson** [comment]
Also, we can just remove zaporylie/composer-drupal-optimizations

**Comment by sarahg** [comment]
@greg-1-anderson Quite a day wrestling with this :D No progress getting this PHP 5.6 test to pass, but I think I better understand what's stuck here:

- The PHP 5.6 test needs `drupal-composer/drupal-scaffold`
- `drupal-composer/drupal-scaffold` is deprecated and not Composer 2 compatible:

```
$  composer scenario php56
./composer.json is valid
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - drupal-composer/drupal-scaffold is locked to version 2.6.1 and an update of this package was not requested.
    - drupal-composer/drupal-scaffold 2.6.1 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
```

I tried using the recommended `drupal/core-composer-scaffold` package for the PHP 5.6 test, but that didn't work out since that one requires PHP 7+.

I think I'm out of ideas, at least for today. Have you run into this on other projects? Any advice? Is dropping PHP 5.6 an option?

**Comment by sarahg** [comment]
Thought about this more, I don't think dropping PHP 5.6 is a realistic or good option, so I tried using Composer 1.10.x for just that test.

That failed as well, so I think I understand this less than I did 2 hours ago, haha. Will give it another go tomorrow.

**Comment by sarahg** [comment]
This branch has gotten messy beyond repair, sorry for the noise. Closing and will open a new one for the Composer 2 changes once they're sorted out. :)

**Pull request closed without merging**
